# Generated by Django 5.2.9 on 2025-12-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_customer_id',
        ),
        migrations.DeleteModel(
            name='PaymentAttempt',
        ),
    ]
